name: Build/Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - maze
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-22.04]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Build on MacOS
        env:
          CSC_LINK: ${{ secrets.APPLE_SIGNING_CERTIFICATE_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build on Linux
        if: matrix.os == 'ubuntu-22.04'
        run: npm run build:linux

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        run: npm run build:win
