name: Build Binary (macOS)

on:
  workflow_dispatch:

jobs:
  build_macos:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: Install Node.js dependencies
        run: |
          npm install

      - name: Build on MacOS
        env:
          CSC_LINK: ${{ secrets.APPLE_SIGNING_CERTIFICATE_BASE64 }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_SIGNING_CERTIFICATE_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: npm run build:mac:no-publish

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Biowatch-macos
          path: |
            dist/Biowatch.dmg
            dist/latest*.yml
